//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace Mix.Desktop.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey Confirm = new ComponentResourceKey(typeof(LangRes), nameof(Confirm));
		public static readonly ComponentResourceKey Login = new ComponentResourceKey(typeof(LangRes), nameof(Login));
	}
}