// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: account.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Mix.Library.Entity.Protos {
  public static partial class Accounts
  {
    static readonly string __ServiceName = "Protos.Accounts";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Mix.Library.Entity.Protos.LoginRequest> __Marshaller_Protos_LoginRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mix.Library.Entity.Protos.LoginRequest.Parser));
    static readonly grpc::Marshaller<global::Mix.Library.Entity.Protos.LoginResponse> __Marshaller_Protos_LoginResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mix.Library.Entity.Protos.LoginResponse.Parser));
    static readonly grpc::Marshaller<global::Mix.Library.Entity.Protos.RegisterRequest> __Marshaller_Protos_RegisterRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mix.Library.Entity.Protos.RegisterRequest.Parser));
    static readonly grpc::Marshaller<global::Mix.Library.Entity.Protos.RegisterResponse> __Marshaller_Protos_RegisterResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mix.Library.Entity.Protos.RegisterResponse.Parser));

    static readonly grpc::Method<global::Mix.Library.Entity.Protos.LoginRequest, global::Mix.Library.Entity.Protos.LoginResponse> __Method_Login = new grpc::Method<global::Mix.Library.Entity.Protos.LoginRequest, global::Mix.Library.Entity.Protos.LoginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_Protos_LoginRequest,
        __Marshaller_Protos_LoginResponse);

    static readonly grpc::Method<global::Mix.Library.Entity.Protos.RegisterRequest, global::Mix.Library.Entity.Protos.RegisterResponse> __Method_Register = new grpc::Method<global::Mix.Library.Entity.Protos.RegisterRequest, global::Mix.Library.Entity.Protos.RegisterResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Register",
        __Marshaller_Protos_RegisterRequest,
        __Marshaller_Protos_RegisterResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Mix.Library.Entity.Protos.AccountReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Accounts</summary>
    [grpc::BindServiceMethod(typeof(Accounts), "BindService")]
    public abstract partial class AccountsBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Mix.Library.Entity.Protos.LoginResponse> Login(global::Mix.Library.Entity.Protos.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Mix.Library.Entity.Protos.RegisterResponse> Register(global::Mix.Library.Entity.Protos.RegisterRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Accounts</summary>
    public partial class AccountsClient : grpc::ClientBase<AccountsClient>
    {
      /// <summary>Creates a new client for Accounts</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AccountsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Accounts that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AccountsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AccountsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AccountsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Mix.Library.Entity.Protos.LoginResponse Login(global::Mix.Library.Entity.Protos.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Mix.Library.Entity.Protos.LoginResponse Login(global::Mix.Library.Entity.Protos.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Mix.Library.Entity.Protos.LoginResponse> LoginAsync(global::Mix.Library.Entity.Protos.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Mix.Library.Entity.Protos.LoginResponse> LoginAsync(global::Mix.Library.Entity.Protos.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual global::Mix.Library.Entity.Protos.RegisterResponse Register(global::Mix.Library.Entity.Protos.RegisterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Register(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Mix.Library.Entity.Protos.RegisterResponse Register(global::Mix.Library.Entity.Protos.RegisterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Register, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Mix.Library.Entity.Protos.RegisterResponse> RegisterAsync(global::Mix.Library.Entity.Protos.RegisterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Mix.Library.Entity.Protos.RegisterResponse> RegisterAsync(global::Mix.Library.Entity.Protos.RegisterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Register, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AccountsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AccountsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AccountsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_Register, serviceImpl.Register).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AccountsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Mix.Library.Entity.Protos.LoginRequest, global::Mix.Library.Entity.Protos.LoginResponse>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_Register, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Mix.Library.Entity.Protos.RegisterRequest, global::Mix.Library.Entity.Protos.RegisterResponse>(serviceImpl.Register));
    }

  }
}
#endregion
